name: Create Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release Tag'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create temporary directory
      run: mkdir temp_dir

    - name: Copy files to temporary directory
      run: |
        find . -maxdepth 1 -not -name 'temp_dir' -not -name '.' -not -name '.git' -not -name '.github' -exec cp -r {} temp_dir/ \;

    - name: Rename directory
      run: mv temp_dir team-schedule

    - name: List files before zipping
      run: ls -R team-schedule

    - name: Zip the folder
      run: |
        zip -r team-schedule-${{ github.event.inputs.tag }}.zip team-schedule \
        -x "team-schedule/.git/*" "team-schedule/.github/*" \
        "team-schedule/package.json" "team-schedule/package-lock.json" \
        "team-schedule/.gitignore" "team-schedule/src/*"

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: team-schedule-${{ github.event.inputs.tag }}.zip
        tag_name: ${{ github.event.inputs.tag }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write
